### ISSUE TITLE
[BUG] tiles are still rendered as whitespace when the content length < pageSize

### ISSUE THREAD

**Issue by mesqueeb** [rocwang/vue-virtual-scroll-grid#152] opened 2021-11-17 05:20 UTC
**Describe the bug**

When I use eg. `:pageSize="40"` and I scroll all the way to the bottom, the final section of the virtual grid will render tile placeholders for content that doesn't exist.

Since a single tile is about 1/3 of the screen height for me, it can render an immense amount of whitespace at the bottom.

Here is the DOM what the placeholder DOM element looks like:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/3253920/142139059-b83da429-f744-4d3a-a421-2c30a305dbf6.png">

You see that the previous one DOM element is the last one I have with content.

**Expected behavior**

The bottom tiles should not be rendered as whitespace when not provided by `pageProvider`. (Eg. the page provider returns only 1 result, and `pageSize` is `40`, then ideally we only render 1 grid row or even better, 1 grid tile.)

**Comment by rocwang** [comment] 2021-11-17 07:40
Thanks for the bug report! It's been fixed in `v1.2.2`.

**Comment by mesqueeb** [comment] 2021-11-17 07:51
@rocwang Thank you so much!
I'm using `2.0.0-alpha.1`, any chance you can fix it on that branch as well? : )

No rush though! thanks so much for all your work!

PS: Sorry I should've mentioned the version I was using!!

**Comment by rocwang** [comment] 2021-11-17 07:59
> I'm using 2.0.0-alpha.1, any chance you can fix it on that branch as well? : )

@mesqueeb I don't I never released a `2.0.0-alpha.1` version on npm or have such branch on Github.
Did you mean some other library you use?

**Comment by mesqueeb** [comment] 2021-11-17 08:23
@rocwang Oh... I was looking at the wrong package!! Sorry 😅  ( I'm so used to looking at @next branches for Vue 3 :P )

Something seems to have gone wrong in the latest version, maybe just for us?

Once I installed it the grid won't render and there's this error:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/3253920/142162542-85d97604-7ed4-4d14-8f3b-ae8ff57abe27.png">

**Comment by rocwang** [comment] 2021-11-17 20:45
Sorry, the screenshot didn't help much. I couldn't replicate the issue.

It looks like [this issue](https://github.com/rocwang/vue-virtual-scroll-grid/issues/112). Maybe try reinstall the package?

If it still doesn't work for you, would you mind rend over a reproducible example? (e.g. a git repo)

**Comment by mesqueeb** [comment] 2021-11-19 05:33
@rocwang 
hmmm, it's very weird, I tried reinstalling everything but can't even build my project now, I get this error : P 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/3253920/142570602-3f93e702-52a4-4013-a557-cca0e640775e.png">

I will try to create a public reproduction

**Comment by mesqueeb** [comment] 2021-11-20 12:39
@rocwang I'm still trying to determine the cause, but cannot find it yet...
The latest version just won't work, but the one before that does.

Could it have something to do with rendering the grid while it's being hidden because some parent element is set to `display: 'none'` (`v-show`) ?

**Comment by rocwang** [comment] 2021-11-21 02:33
> @rocwang Oh... I was looking at the wrong package!! Sorry 😅 ( I'm so used to looking at @next branches for Vue 3 :P )
> 
> Something seems to have gone wrong in the latest version, maybe just for us?
> 
> Once I installed it the grid won't render and there's this error: <img alt="image" width="689" src="https://user-images.githubusercontent.com/3253920/142162542-85d97604-7ed4-4d14-8f3b-ae8ff57abe27.png">

Although https://github.com/rocwang/vue-virtual-scroll-grid/releases/tag/v1.2.3 adressed #154 instead of your error above directly, give it a try it maybe?

**Comment by mesqueeb** [comment] 2021-11-22 06:32
@rocwang I have just tested on 1.2.3, same issue.

I have just emailed your our repo with steps for you to open it on your end.

If you have some time we would greatly appreciate it.

**Comment by rocwang** [comment] 2021-11-22 10:11
Thanks for sending over the example over email.

I managed to get it to work by fixing the version of vue in the project to `3.2.22` as `vue-virtual-scroll-grid@1.2.3` was built and tested against `vue@3.2.22`. It looks like it has something to do with multiple versions of vue packages sitting under the same project, but I'm pretty sure `vue-virtual-scroll-grid` doesn't  include vue in the package.

Another change I made was removing the `peerDependencies` of `vue` from your `db` package as I didn't see it's used there.

While my fix works, it looks like your project use Quasar, which has its own dependant vue version. So I think the best solution might be upgrading Quasar to some version that depends on vue `3.2.22+`. Don't take my fix as the final solution.

See:

* https://github.com/vuejs/vue-next/issues/4344
* https://github.com/vuejs/vue-next/issues/4478

A fixing patch is emailed to you.

**Comment by mesqueeb** [comment] 2021-11-24 09:21
@rocwang hey Roc!

Thank you very much for resolving my issue with the dependencies.

I just tried the latest version, but still found some issues.

Eg. When the pageSize is `40` and the array I put in is about `69` long, I still see about 11 tiles that should not render but are being rendered.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/3253920/143210027-056e0193-493f-4d68-a77a-4d73884fc70a.png">

On mobile view for us it has 3 tiles per row, and therefore will take up many many times the screen height.

Can you look into the issue again? Let me know if you need anything from me.

Thank you very much.

**Comment by rocwang** [comment] 2021-11-24 22:33
@mesqueeb 

I try to replicate the issue with your parameters (`pageSize = 40`, `length = 69`) under `vur-virtual-scroll-grid@1.2.3` using this minimal repo: https://github.com/rocwang/vvsg-issue-152. However, it looks OK to me there and no item would be rendered beyond the 69th item.

Could you have a play there and see if you can see the issue. Or consider double checking the installed version of vur-virtual-scroll-grid, as the symptom was found in v1.2.1 indeed.

**Comment by rocwang** [comment] 2021-11-24 22:36
@mesqueeb 
I had another play.
I see, it looks like the bug happens when the viewport is resized. Will look into that.

**Comment by mesqueeb** [comment] 2021-11-24 23:18
@rocwang thank you very much. I will send you another reproduction later today. Thank you for your patience.

**Comment by rocwang** [comment] 2021-12-22 01:17
@mesqueeb I wonder if this is still an issue to you?

**Comment by mesqueeb** [comment] 2021-12-22 02:16
@rocwang i'll check and let you know soon!!

**Comment by rocwang** [comment] 2022-01-17 20:45
Given the inactivity of this ticket, I'm going to close it.
Feel free to reopen it if needed.

**Closed by rocwang** 2022-01-17 20:45 UTC
Labels: bug, released
